apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::824408445920:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-FWJH7C04WEXF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::824408445920:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-30T19:26:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1342"
  uid: c41b7ce1-e676-4454-b5c3-0fb3657a7d01
